#!/usr/bin/env node
/**
 * optimize-images.mjs — SOTA image optimization for mariusklimke.de.
 *
 * Converts every raster image (jpg/png) in Works/, about/, shared/ and the
 * root-level portfolio images into:
 *   - AVIF (best compression, modern browsers)        quality 55
 *   - WebP (universally supported, reliable middle)   quality 80
 * plus a -1080 (1080px wide) variant for images wider than LARGE_W threshold,
 * so pages can serve responsive srcset candidates.
 *
 * Originals are kept as fallback; the HTML <picture> markup is generated by
 * add-picture.mjs (runs after this script).
 *
 * Sources for defaults (2026):
 *   - AVIF best bytes, WebP reliable middle: requestmetrics.com/web-performance/high-performance-images/
 *   - WebP quality below 80 degrades visibly: reddit.com/r/webdev/comments/vjq5ei/
 *   - AVIF ~50-60 quality is the sweet spot: digiforge.dev/knowledge-base/image-optimization-2026-avif-webp-responsive-lazy-loading
 *
 * Usage: node scripts/optimize-images.mjs [--dry-run]
 */
import sharp from "sharp";
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Images wider than this get a second, 1080px-wide srcset candidate.
export const LARGE_W = 1280;
export const VARIANT_SUFFIX = "-1080";

const WEBP_QUALITY = 80;
const AVIF_QUALITY = 55;

const IMG_RE = /\.(jpe?g|png)$/i;
const SCAN_DIRS = ["Works", "about", "shared"];
// Root-level images (e.g. photomarius.jpg) — keep explicit to avoid scanning
// scripts/, deploy/, .git/ etc.
const ROOT_IMAGES = ["photomarius.jpg"];

function collectImages(dir, out) {
  for (const entry of readdirSync(dir)) {
    if (entry === ".git" || entry === "node_modules") continue;
    const p = path.join(dir, entry);
    const st = statSync(p);
    if (st.isDirectory()) collectImages(p, out);
    else if (IMG_RE.test(entry)) out.push(p);
  }
  return out;
}

function log(...args) {
  console.log("[optimize-images]", ...args);
}

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const files = [];
  for (const d of SCAN_DIRS) collectImages(path.join(REPO_ROOT, d), files);
  for (const f of ROOT_IMAGES) {
    const p = path.join(REPO_ROOT, f);
    if (existsSync(p)) files.push(p);
  }

  log(`found ${files.length} images`);

  let converted = 0;
  let bytesBefore = 0;
  let bytesAfter = 0;
  const errors = [];

  for (const file of files) {
    const meta = await sharp(file).metadata();
    const { width = 0, height = 0 } = meta;
    if (!width || !height) {
      errors.push(`${file}: no dimensions`);
      continue;
    }

    const stem = file.replace(IMG_RE, "");
    const targets = [];

    if (width > LARGE_W) {
      // Responsive: full-width + 1080px candidate.
      targets.push(
        { out: `${stem}${VARIANT_SUFFIX}.webp`, resizeW: 1080, fmt: "webp", q: WEBP_QUALITY },
        { out: `${stem}${VARIANT_SUFFIX}.avif`, resizeW: 1080, fmt: "avif", q: AVIF_QUALITY },
      );
    }
    targets.push(
      { out: `${stem}.webp`, resizeW: null, fmt: "webp", q: WEBP_QUALITY },
      { out: `${stem}.avif`, resizeW: null, fmt: "avif", q: AVIF_QUALITY },
    );

    const srcBytes = statSync(file).size;
    for (const t of targets) {
      // Skip if output exists and is newer than the source (idempotent re-runs).
      if (existsSync(t.out) && statSync(t.out).mtimeMs >= statSync(file).mtimeMs) continue;
      if (dryRun) continue;

      let pipeline = sharp(file).rotate(); // honor EXIF orientation
      if (t.resizeW) pipeline = pipeline.resize({ width: t.resizeW, withoutEnlargement: true });
      let outBuf;
      try {
        if (t.fmt === "webp") outBuf = await pipeline.webp({ quality: t.q, effort: 4 }).toBuffer();
        else outBuf = await pipeline.avif({ quality: t.q, effort: 4 }).toBuffer();
      } catch (e) {
        errors.push(`${file} -> ${t.out}: ${e.message}`);
        continue;
      }
      writeFileSync(t.out, outBuf);
      bytesBefore += srcBytes;
      bytesAfter += outBuf.length;
      converted++;
      log(`  ${path.relative(REPO_ROOT, t.out)} (${(outBuf.length / 1024).toFixed(0)}K)`);
    }
  }

  if (dryRun) {
    log("dry-run: no files written");
    return;
  }
  const savedPct = bytesBefore ? ((1 - bytesAfter / bytesBefore) * 100).toFixed(1) : "0";
  log(`done: ${converted} files written, ~${savedPct}% size reduction on processed sources`);
  if (errors.length) {
    console.error("[optimize-images] errors:");
    for (const e of errors) console.error("  " + e);
    process.exitCode = 1;
  }
}

// Only run when executed directly (also imported by add-picture.mjs for constants).
const isMain = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;
if (isMain) {
  main();
}
